name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: |
          pnpm build
          mv dist infra/dist

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./infra
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/rakdotdev.space:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH context
        run: |
          touch ~/.ssh/r101_linode
          echo "${{ secrets.PRIVATE_KEY }}" >> ~/.ssh/r101_linode

      - name: SSH to VPS
        run: |
          scp -i ~/.ssh/r101_linode infra/docker-compose.yml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/docker-compose.yml
          ssh -i ~/.ssh/r101_linode ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}
          cd /
          IMAGE_TAG=${{ github.sha }} docker compose up -d
