name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: |
          pnpm build
          mv dist infra/dist

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./infra
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/rakdotdev.space:${{ github.sha }}

      - name: Trigger new deployment
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/r101_linode
          chmod 400 ~/.ssh/r101_linode
          scp -o StrictHostKeyChecking=no -i ~/.ssh/r101_linode infra/docker-compose.yml $VPS_USER@$VPS_HOST:~/docker-compose.yml
          scp -o StrictHostKeyChecking=no -i ~/.ssh/r101_linode infra/conf.d/rakdotdev.conf $VPS_USER@$VPS_HOST:/etc/nginx/conf.d/rakdotdev.space.conf
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/r101_linode $VPS_USER@$VPS_HOST "IMAGE_TAG=${{ github.sha }} docker compose up -d; nginx -s reload"
